---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves   
      Did gyre and gimble in the wabe:   
All mimsy were the borogoves,   
      And the mome raths outgrabe.   
  
“Beware the Jabberwock, my son!   

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

I walked down alone Sunday after church  
   To the place where John has been cutting trees  
To see for myself about the birch  
   He said I could have to bush my peas.  
  
The sun in the new-cut narrow gap  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Autumn brushes her hair slowly  
Letting the glorious colors  
flow gently to the earth below.  
Showing off vibrant colors   
 in contrast to summer's green dress.  
 Out doing the starkness,  
of winter's white coat.  
Autumn compares the mutable  
shades of spring to her fall  
Giving a sigh ,end of another season.  
She packs her brush   
as frost touches her tips.  